package EtudiantModule;


/**
* EtudiantModule/_EtudiantStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Etudiant.idl
* Thursday, December 4, 2025 5:15:20 PM CET
*/


// Interface Etudiant
public class _EtudiantStub extends org.omg.CORBA.portable.ObjectImpl implements EtudiantModule.Etudiant
{


  // Ajouter une épreuve pour un étudiant
  public boolean ajouterUneEpreuve (String nomEtudiant, EtudiantModule.Epreuve epreuve)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("ajouterUneEpreuve", true);
                $out.write_string (nomEtudiant);
                EtudiantModule.EpreuveHelper.write ($out, epreuve);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return ajouterUneEpreuve (nomEtudiant, epreuve        );
            } finally {
                _releaseReply ($in);
            }
  } // ajouterUneEpreuve


  // Lister les épreuves d'un étudiant
  public EtudiantModule.Epreuve[] listeDesEpreuves (String nomEtudiant)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listeDesEpreuves", true);
                $out.write_string (nomEtudiant);
                $in = _invoke ($out);
                EtudiantModule.Epreuve $result[] = EtudiantModule.ListeEpreuvesHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listeDesEpreuves (nomEtudiant        );
            } finally {
                _releaseReply ($in);
            }
  } // listeDesEpreuves


  // Calculer la moyenne d'un étudiant
  public float calculerLaMoyenne (String nomEtudiant)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("calculerLaMoyenne", true);
                $out.write_string (nomEtudiant);
                $in = _invoke ($out);
                float $result = $in.read_float ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return calculerLaMoyenne (nomEtudiant        );
            } finally {
                _releaseReply ($in);
            }
  } // calculerLaMoyenne


  // Lister les 10 premiers étudiants
  public EtudiantModule.EtudiantInfo[] listerLes10Premiers ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listerLes10Premiers", true);
                $in = _invoke ($out);
                EtudiantModule.EtudiantInfo $result[] = EtudiantModule.ListeEtudiantsHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listerLes10Premiers (        );
            } finally {
                _releaseReply ($in);
            }
  } // listerLes10Premiers

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:EtudiantModule/Etudiant:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     com.sun.corba.se.impl.orbutil.IORCheckImpl.check(str, "EtudiantModule._EtudiantStub");
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _EtudiantStub
