package EtudiantModule;

/**
* EtudiantModule/EpreuveHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Etudiant.idl
* Thursday, December 4, 2025 5:15:20 PM CET
*/

public final class EpreuveHolder implements org.omg.CORBA.portable.Streamable
{
  public EtudiantModule.Epreuve value = null;

  public EpreuveHolder ()
  {
  }

  public EpreuveHolder (EtudiantModule.Epreuve initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = EtudiantModule.EpreuveHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    EtudiantModule.EpreuveHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return EtudiantModule.EpreuveHelper.type ();
  }

}
