package EtudiantModule;


/**
* EtudiantModule/Epreuve.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Etudiant.idl
* Thursday, December 4, 2025 5:15:20 PM CET
*/

public final class Epreuve implements org.omg.CORBA.portable.IDLEntity
{
  public String nom = null;
  public float note = (float)0;
  public int coefficient = (int)0;

  public Epreuve ()
  {
  } // ctor

  public Epreuve (String _nom, float _note, int _coefficient)
  {
    nom = _nom;
    note = _note;
    coefficient = _coefficient;
  } // ctor

} // class Epreuve
