package EtudiantModule;


/**
* EtudiantModule/EtudiantInfoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Etudiant.idl
* Thursday, December 4, 2025 5:15:20 PM CET
*/

abstract public class EtudiantInfoHelper
{
  private static String  _id = "IDL:EtudiantModule/EtudiantInfo:1.0";

  public static void insert (org.omg.CORBA.Any a, EtudiantModule.EtudiantInfo that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static EtudiantModule.EtudiantInfo extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "nom",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_float);
          _members0[1] = new org.omg.CORBA.StructMember (
            "moyenne",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (EtudiantModule.EtudiantInfoHelper.id (), "EtudiantInfo", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static EtudiantModule.EtudiantInfo read (org.omg.CORBA.portable.InputStream istream)
  {
    EtudiantModule.EtudiantInfo value = new EtudiantModule.EtudiantInfo ();
    value.nom = istream.read_string ();
    value.moyenne = istream.read_float ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, EtudiantModule.EtudiantInfo value)
  {
    ostream.write_string (value.nom);
    ostream.write_float (value.moyenne);
  }

}
