package EtudiantModule;


/**
* EtudiantModule/EtudiantPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Etudiant.idl
* Thursday, December 4, 2025 5:15:20 PM CET
*/


// Interface Etudiant
public abstract class EtudiantPOA extends org.omg.PortableServer.Servant
 implements EtudiantModule.EtudiantOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("ajouterUneEpreuve", new java.lang.Integer (0));
    _methods.put ("listeDesEpreuves", new java.lang.Integer (1));
    _methods.put ("calculerLaMoyenne", new java.lang.Integer (2));
    _methods.put ("listerLes10Premiers", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // Ajouter une épreuve pour un étudiant
       case 0:  // EtudiantModule/Etudiant/ajouterUneEpreuve
       {
         String nomEtudiant = in.read_string ();
         EtudiantModule.Epreuve epreuve = EtudiantModule.EpreuveHelper.read (in);
         boolean $result = false;
         $result = this.ajouterUneEpreuve (nomEtudiant, epreuve);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }


  // Lister les épreuves d'un étudiant
       case 1:  // EtudiantModule/Etudiant/listeDesEpreuves
       {
         String nomEtudiant = in.read_string ();
         EtudiantModule.Epreuve $result[] = null;
         $result = this.listeDesEpreuves (nomEtudiant);
         out = $rh.createReply();
         EtudiantModule.ListeEpreuvesHelper.write (out, $result);
         break;
       }


  // Calculer la moyenne d'un étudiant
       case 2:  // EtudiantModule/Etudiant/calculerLaMoyenne
       {
         String nomEtudiant = in.read_string ();
         float $result = (float)0;
         $result = this.calculerLaMoyenne (nomEtudiant);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }


  // Lister les 10 premiers étudiants
       case 3:  // EtudiantModule/Etudiant/listerLes10Premiers
       {
         EtudiantModule.EtudiantInfo $result[] = null;
         $result = this.listerLes10Premiers ();
         out = $rh.createReply();
         EtudiantModule.ListeEtudiantsHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:EtudiantModule/Etudiant:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Etudiant _this() 
  {
    return EtudiantHelper.narrow(
    super._this_object());
  }

  public Etudiant _this(org.omg.CORBA.ORB orb) 
  {
    return EtudiantHelper.narrow(
    super._this_object(orb));
  }


} // class EtudiantPOA
