package EtudiantModule;


/**
* EtudiantModule/EtudiantOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Etudiant.idl
* Thursday, December 4, 2025 5:15:20 PM CET
*/


// Interface Etudiant
public interface EtudiantOperations 
{

  // Ajouter une épreuve pour un étudiant
  boolean ajouterUneEpreuve (String nomEtudiant, EtudiantModule.Epreuve epreuve);

  // Lister les épreuves d'un étudiant
  EtudiantModule.Epreuve[] listeDesEpreuves (String nomEtudiant);

  // Calculer la moyenne d'un étudiant
  float calculerLaMoyenne (String nomEtudiant);

  // Lister les 10 premiers étudiants
  EtudiantModule.EtudiantInfo[] listerLes10Premiers ();
} // interface EtudiantOperations
