package EtudiantModule;

/**
* EtudiantModule/EtudiantHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Etudiant.idl
* Thursday, December 4, 2025 5:15:20 PM CET
*/


// Interface Etudiant
public final class EtudiantHolder implements org.omg.CORBA.portable.Streamable
{
  public EtudiantModule.Etudiant value = null;

  public EtudiantHolder ()
  {
  }

  public EtudiantHolder (EtudiantModule.Etudiant initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = EtudiantModule.EtudiantHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    EtudiantModule.EtudiantHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return EtudiantModule.EtudiantHelper.type ();
  }

}
