package EtudiantModule;


/**
* EtudiantModule/Etudiant.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Etudiant.idl
* Thursday, December 4, 2025 5:15:20 PM CET
*/


// Interface Etudiant
public interface Etudiant extends EtudiantOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Etudiant
