package EtudiantModule;


/**
* EtudiantModule/EtudiantInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Etudiant.idl
* Thursday, December 4, 2025 5:15:20 PM CET
*/

public final class EtudiantInfo implements org.omg.CORBA.portable.IDLEntity
{
  public String nom = null;
  public float moyenne = (float)0;

  public EtudiantInfo ()
  {
  } // ctor

  public EtudiantInfo (String _nom, float _moyenne)
  {
    nom = _nom;
    moyenne = _moyenne;
  } // ctor

} // class EtudiantInfo
