package EtudiantModule;


/**
* EtudiantModule/ListeEpreuvesHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Etudiant.idl
* Thursday, December 4, 2025 5:15:20 PM CET
*/


// Séquence d'épreuves
abstract public class ListeEpreuvesHelper
{
  private static String  _id = "IDL:EtudiantModule/ListeEpreuves:1.0";

  public static void insert (org.omg.CORBA.Any a, EtudiantModule.Epreuve[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static EtudiantModule.Epreuve[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = EtudiantModule.EpreuveHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (EtudiantModule.ListeEpreuvesHelper.id (), "ListeEpreuves", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static EtudiantModule.Epreuve[] read (org.omg.CORBA.portable.InputStream istream)
  {
    EtudiantModule.Epreuve value[] = null;
    int _len0 = istream.read_long ();
    value = new EtudiantModule.Epreuve[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = EtudiantModule.EpreuveHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, EtudiantModule.Epreuve[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      EtudiantModule.EpreuveHelper.write (ostream, value[_i0]);
  }

}
