package EtudiantModule;


/**
* EtudiantModule/ListeEtudiantsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Etudiant.idl
* Thursday, December 4, 2025 5:15:20 PM CET
*/


// Séquence d'étudiants
public final class ListeEtudiantsHolder implements org.omg.CORBA.portable.Streamable
{
  public EtudiantModule.EtudiantInfo value[] = null;

  public ListeEtudiantsHolder ()
  {
  }

  public ListeEtudiantsHolder (EtudiantModule.EtudiantInfo[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = EtudiantModule.ListeEtudiantsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    EtudiantModule.ListeEtudiantsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return EtudiantModule.ListeEtudiantsHelper.type ();
  }

}
