package EtudiantModule;


/**
* EtudiantModule/ListeEpreuvesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Etudiant.idl
* Thursday, December 4, 2025 5:15:20 PM CET
*/


// Séquence d'épreuves
public final class ListeEpreuvesHolder implements org.omg.CORBA.portable.Streamable
{
  public EtudiantModule.Epreuve value[] = null;

  public ListeEpreuvesHolder ()
  {
  }

  public ListeEpreuvesHolder (EtudiantModule.Epreuve[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = EtudiantModule.ListeEpreuvesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    EtudiantModule.ListeEpreuvesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return EtudiantModule.ListeEpreuvesHelper.type ();
  }

}
