package PromotionModule;

/**
* PromotionModule/EpreuveHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Promotion.idl
* Thursday, December 4, 2025 5:15:52 PM CET
*/

public final class EpreuveHolder implements org.omg.CORBA.portable.Streamable
{
  public PromotionModule.Epreuve value = null;

  public EpreuveHolder ()
  {
  }

  public EpreuveHolder (PromotionModule.Epreuve initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PromotionModule.EpreuveHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PromotionModule.EpreuveHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PromotionModule.EpreuveHelper.type ();
  }

}
