package PromotionModule;


/**
* PromotionModule/EpreuveHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Promotion.idl
* Thursday, December 4, 2025 5:15:52 PM CET
*/

abstract public class EpreuveHelper
{
  private static String  _id = "IDL:PromotionModule/Epreuve:1.0";

  public static void insert (org.omg.CORBA.Any a, PromotionModule.Epreuve that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static PromotionModule.Epreuve extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "nom",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_float);
          _members0[1] = new org.omg.CORBA.StructMember (
            "note",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[2] = new org.omg.CORBA.StructMember (
            "coefficient",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (PromotionModule.EpreuveHelper.id (), "Epreuve", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static PromotionModule.Epreuve read (org.omg.CORBA.portable.InputStream istream)
  {
    PromotionModule.Epreuve value = new PromotionModule.Epreuve ();
    value.nom = istream.read_string ();
    value.note = istream.read_float ();
    value.coefficient = istream.read_long ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, PromotionModule.Epreuve value)
  {
    ostream.write_string (value.nom);
    ostream.write_float (value.note);
    ostream.write_long (value.coefficient);
  }

}
