package PromotionModule;

/**
* PromotionModule/EtudiantInfoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Promotion.idl
* Thursday, December 4, 2025 5:15:52 PM CET
*/

public final class EtudiantInfoHolder implements org.omg.CORBA.portable.Streamable
{
  public PromotionModule.EtudiantInfo value = null;

  public EtudiantInfoHolder ()
  {
  }

  public EtudiantInfoHolder (PromotionModule.EtudiantInfo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PromotionModule.EtudiantInfoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PromotionModule.EtudiantInfoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PromotionModule.EtudiantInfoHelper.type ();
  }

}
