package PromotionModule;


/**
* PromotionModule/ListeEtudiantsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Promotion.idl
* Thursday, December 4, 2025 5:15:52 PM CET
*/


// Séquence d'étudiants
public final class ListeEtudiantsHolder implements org.omg.CORBA.portable.Streamable
{
  public PromotionModule.EtudiantInfo value[] = null;

  public ListeEtudiantsHolder ()
  {
  }

  public ListeEtudiantsHolder (PromotionModule.EtudiantInfo[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PromotionModule.ListeEtudiantsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PromotionModule.ListeEtudiantsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PromotionModule.ListeEtudiantsHelper.type ();
  }

}
