package PromotionModule;


/**
* PromotionModule/ListeEpreuvesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Promotion.idl
* Thursday, December 4, 2025 5:15:52 PM CET
*/


// Séquence d'épreuves
public final class ListeEpreuvesHolder implements org.omg.CORBA.portable.Streamable
{
  public PromotionModule.Epreuve value[] = null;

  public ListeEpreuvesHolder ()
  {
  }

  public ListeEpreuvesHolder (PromotionModule.Epreuve[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PromotionModule.ListeEpreuvesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PromotionModule.ListeEpreuvesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PromotionModule.ListeEpreuvesHelper.type ();
  }

}
