package PromotionModule;


/**
* PromotionModule/PromotionHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Promotion.idl
* Thursday, December 4, 2025 5:15:52 PM CET
*/


// Interface Promotion
abstract public class PromotionHelper
{
  private static String  _id = "IDL:PromotionModule/Promotion:1.0";

  public static void insert (org.omg.CORBA.Any a, PromotionModule.Promotion that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static PromotionModule.Promotion extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (PromotionModule.PromotionHelper.id (), "Promotion");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static PromotionModule.Promotion read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_PromotionStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, PromotionModule.Promotion value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static PromotionModule.Promotion narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof PromotionModule.Promotion)
      return (PromotionModule.Promotion)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      PromotionModule._PromotionStub stub = new PromotionModule._PromotionStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static PromotionModule.Promotion unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof PromotionModule.Promotion)
      return (PromotionModule.Promotion)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      PromotionModule._PromotionStub stub = new PromotionModule._PromotionStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
