package PromotionModule;


/**
* PromotionModule/PromotionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Promotion.idl
* Thursday, December 4, 2025 5:15:52 PM CET
*/


// Interface Promotion
public interface PromotionOperations 
{

  // Créer un nouvel étudiant dans la promotion
  boolean creerEtudiant (String nomEtudiant);

  // Rechercher un étudiant précédemment enregistré
  boolean rechercherUnEtudiant (String nomEtudiant);

  // Calcul du ratio de réussite
  float calculerRatioReussite ();

  // Obtenir la moyenne générale de toute la promotion
  float obtenirMoyenneGenerale ();
} // interface PromotionOperations
