package PromotionModule;


/**
* PromotionModule/PromotionPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Promotion.idl
* Thursday, December 4, 2025 5:15:52 PM CET
*/


// Interface Promotion
public abstract class PromotionPOA extends org.omg.PortableServer.Servant
 implements PromotionModule.PromotionOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("creerEtudiant", new java.lang.Integer (0));
    _methods.put ("rechercherUnEtudiant", new java.lang.Integer (1));
    _methods.put ("calculerRatioReussite", new java.lang.Integer (2));
    _methods.put ("obtenirMoyenneGenerale", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // Créer un nouvel étudiant dans la promotion
       case 0:  // PromotionModule/Promotion/creerEtudiant
       {
         String nomEtudiant = in.read_string ();
         boolean $result = false;
         $result = this.creerEtudiant (nomEtudiant);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }


  // Rechercher un étudiant précédemment enregistré
       case 1:  // PromotionModule/Promotion/rechercherUnEtudiant
       {
         String nomEtudiant = in.read_string ();
         boolean $result = false;
         $result = this.rechercherUnEtudiant (nomEtudiant);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }


  // Calcul du ratio de réussite
       case 2:  // PromotionModule/Promotion/calculerRatioReussite
       {
         float $result = (float)0;
         $result = this.calculerRatioReussite ();
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }


  // Obtenir la moyenne générale de toute la promotion
       case 3:  // PromotionModule/Promotion/obtenirMoyenneGenerale
       {
         float $result = (float)0;
         $result = this.obtenirMoyenneGenerale ();
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:PromotionModule/Promotion:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Promotion _this() 
  {
    return PromotionHelper.narrow(
    super._this_object());
  }

  public Promotion _this(org.omg.CORBA.ORB orb) 
  {
    return PromotionHelper.narrow(
    super._this_object(orb));
  }


} // class PromotionPOA
