package PromotionModule;

/**
* PromotionModule/PromotionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Promotion.idl
* Thursday, December 4, 2025 5:15:52 PM CET
*/


// Interface Promotion
public final class PromotionHolder implements org.omg.CORBA.portable.Streamable
{
  public PromotionModule.Promotion value = null;

  public PromotionHolder ()
  {
  }

  public PromotionHolder (PromotionModule.Promotion initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PromotionModule.PromotionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PromotionModule.PromotionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PromotionModule.PromotionHelper.type ();
  }

}
